### ISSUE TITLE
Restrict the access to this page only to users coming from internal network

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#481] opened 2021-09-24 11:57 UTC
`MapStore2/internal-login.html` have to be restricted to user coming from internal network (or VPN?)
 (DevOps)

**Comment by tdipisa** [comment] 2021-09-24 12:12
@randomorder since #471 has been merged in master, we need to deploy it on test. Then for production we have to do what reported in description. That update must be in production before Sept 30.

**Comment by randomorder** [comment] 2021-09-28 09:32
war deployed in Prod @tdipisa 
todo:
- set the reverse proxy to block access to public IP addresses for MapStore2/internal-login.html

**Comment by tdipisa** [comment] 2021-09-28 12:31
@randomorder I've asked the client if this is confirmed or we can skip this activity. Let's wait for the client feedback first.

**Comment by tdipisa** [comment] 2021-09-29 15:10
@randomorder the client already implemented this

**Closed by tdipisa** 2021-09-29 15:10 UTC
Labels: C040-COMUNE_GE-2021-SUPPORT, DevOps
