### ISSUE TITLE
Investigation required on heavy CPU utilization for GeoServer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#491] opened 2021-10-29 10:03 UTC
From the client:

>come accennato nelle ultime volte al telefono, i sistemisti (ma anche noi tramite la console geoserver) hanno riscontrato una involuzione generale delle performances nella macchina
http://vm-linuxgeobe1.comune.genova.it:8080/geoserver/

>Nelle cpu si riscontra un carico consistente, quasi il 100%, tutti i giorni nelle ultime settimane
Riuscite a controllare quale sia il problema?

Related GS internal ticket is:
https://github.com/geosolutions-it/DevOps/issues/782

**Comment by tdipisa** [comment] 2021-11-04 08:32
Currently blocked by https://github.com/geosolutions-it/DevOps/issues/782

**Comment by tdipisa** [comment] 2021-11-05 17:19
@randomorder in the status meeting today, the client reported me that the problem happened again and that it is frequent. From some client checks it seems that the issue is with the geobe1 geoserver that is more overloaded than geobe2 for some reason. Can we spend some time to investigate this? 

I can imagine one of the following, what else?
- A problem with the balancer that is not properly balancing requests between the two geoservers
- Someone is performing for some reasons many requests directly to geobe1

**Comment by randomorder** [comment] 2021-11-05 17:47
> A problem with the balancer that is not properly balancing requests between the two geoservers

We have analytics, we can easily check the busyness of the two instances

I took logs, jstack and jmap. The situation is a bit different this time @tdipisa . No sign of OOM in the logs today
Let's check kibana, the logs and stacks next week

I've restarted the service on geobe1

**Comment by tdipisa** [comment] 2021-11-05 17:54
Thank you @randomorder keep me updated as soon as you can please.

**Comment by randomorder** [comment] 2021-11-05 17:57
Files uploaded [here](https://www.dropbox.com/work/GeoSolutions/2021/COMUNE_GENOVA_C040/C040-COMUNE_GE-2021-SUPPORT/05/11/2021%20high%20cpu%20issue)

Could we have a DEV look at it @nmco?

**Comment by nmco** [comment] 2021-11-08 11:00
Sure @randomorder, @fernandor777 can you do the initial assessment? (MAX 1 HOUR).

**Comment by tdipisa** [comment] 2021-11-10 08:54
@nmco any news on this?

**Comment by tdipisa** [comment] 2021-11-10 11:02
@randomorder please ensure that watchdogs are properly working too as you mentioned in [#494](https://github.com/geosolutions-it/MapStore2-C040/issues/494#issuecomment-965008798)

**Comment by randomorder** [comment] 2021-11-10 11:07
I found a problem
Watchdog is disabled on Sitgeobe1. Maybe was disabled during the release on Prod and never re-enabled. That explains why we only had the problem on geobe1. We still need to understand the root cause

I'm enableing the WD now.  For reference the WD request is:
```
GSURL=http://127.0.0.1:8080/geoserver
WFSURL="$GSURL/wfs?service=wfs&version=1.1.0&request=GetFeature&typeNames=PROTCIV:V_NOMI_FIUME_AREA&maxfeatures=1"

```

**Comment by tdipisa** [comment] 2021-11-10 11:09
Thank you @randomorder. Let's wait for @nmco then.

**Comment by tdipisa** [comment] 2021-11-15 09:43
@nmco I need some news for this. Can you please let me know when you can have some feedbacks?

**Comment by randomorder** [comment] 2021-11-15 09:50
latest dumps and logs [here](https://www.dropbox.com/s/4o9v5vu99epgz0y/comunege_high_cpu_15_nov_2021.zip?dl=0)

**Comment by randomorder** [comment] 2021-11-22 13:22
ping @nmco

**Comment by simboss** [comment] 2021-12-01 13:14
@aaime can you do a time capped investigation on this one?
We just to read  your analysis on the issue to decide what to do next...

**Comment by aaime** [comment] 2021-12-01 14:05
Weird one. The stack traces only report this:

```
"ajp-nio-0.0.0.0-8009-exec-54" #368170 daemon prio=5 os_prio=0 tid=0x00007f2c0c00e800 nid=0x1e39 runnable [0x00007f2b957f3000]
   java.lang.Thread.State: RUNNABLE
	at java.util.TreeMap.put(TreeMap.java:568)
	at java.util.TreeSet.add(TreeSet.java:255)
	at org.geoserver.gwc.layer.StyleParameterFilter.setLayer(StyleParameterFilter.java:197)
	at org.geoserver.gwc.layer.TileLayerInfoUtil.checkAutomaticStyles(TileLayerInfoUtil.java:162)
	at org.geoserver.gwc.layer.TileLayerInfoUtil.checkAutomaticStyles(TileLayerInfoUtil.java:140)
	at org.geoserver.gwc.layer.GeoServerTileLayer.lambda$getPublishedInfo$0(GeoServerTileLayer.java:359)
	at org.geoserver.gwc.layer.GeoServerTileLayer$$Lambda$223/1414347603.apply(Unknown Source)
	at java.util.concurrent.atomic.AtomicReference.accumulateAndGet(AtomicReference.java:227)
	at org.geoserver.gwc.layer.GeoServerTileLayer.getPublishedInfo(GeoServerTileLayer.java:344)
	at org.geoserver.gwc.layer.GeoServerTileLayer.isEnabled(GeoServerTileLayer.java:307)
	at org.geoserver.gwc.GWC.dispatch(GWC.java:752)
```

At first, it would seem like a simple, ignorable bit... except that I recently stumbled into a bit of code Gabriel wrote, appearing in that stack trace, that got modified in this PR:

https://github.com/geoserver/geoserver/pull/5301

The PR got merged on master only, the server from Genova is using the original bits from Gabriel... which are really impenetrable to me. The new version is a bit more readable (it's a lazy init, no idea why a while loop is needed though, it should never get a null). The original code, in all of its abomination, is here:

https://github.com/geoserver/geoserver/blame/2.20.x/src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java#L358

I'm guessing that if N threads start fighting to create the published info stored in the thread-local, and for some reason end up with non identical objects, they could end up looping "forever" (I mean, it seems so unlikely, but still). The new code instead should loop at most once, it just ends up picking the PublishedInfo that "won the fight" (the last one). I'm also guessing that a situation where a layer has lots of styles, making ``TileLayerInfoUtil.checkAutomaticStyles(catalogLayer, info);`` slow, would increase the odds of that happening.

**Comment by simboss** [comment] 2021-12-01 14:12
@aaime thanks for the detailed explanation, however it is not clear to me what you are suggesting to do.
Can you please, clarify?

**Comment by aaime** [comment] 2021-12-01 14:16
I guess we can backport that PR and see if that helps. It should.

**Comment by simboss** [comment] 2021-12-01 18:21
@aaime let's backport as back as possible, possibly to 2.18 as well.

**Comment by aaime** [comment] 2021-12-02 11:33
Backport pull requests issued, all the way down to 2.18.x. Will report back when they get merged.

**Comment by simboss** [comment] 2021-12-02 18:11
great @aaime.
ping me when done...

**Comment by aaime** [comment] 2021-12-03 10:33
All backports merged, nightly builds will take their time to be produced, most will be ready tomorrow.
Mind, [2.18.x hasn't been built since Sept 10th 2021](https://build.geoserver.org/geoserver/2.18.x/), if you need a 2.18.x build, it will have to be done by hand.

**Comment by simboss** [comment] 2021-12-03 14:25
@aaime can we reactive the build just for now?

**Comment by aaime** [comment] 2021-12-03 14:31
@simboss the build is gone, we'd have to re-create it. Jody has been cleaning up all old builds lately, if you check the nightly builds latest date of a given series, they match with the release of the RC of the corresponding new series.

**Comment by aaime** [comment] 2021-12-03 14:38
Thinking out loud, do you want me to discuss this at the next PSC meeting, or send a mail to the gs-devel list? About keeping the older builds for 6 more months after the branch has been discontinued?

**Comment by simboss** [comment] 2021-12-03 14:39
@aaime good, thanks for the info.
I might ask you to prepare a WAR then.

**Comment by simboss** [comment] 2021-12-03 14:58
That would be a good idea.
We can provide the resources that are needed, just in case.

**Comment by tdipisa** [comment] 2021-12-06 10:38
@aaime, the Comune di Genova is using GS 2.19.1. Is it possible to have a patched JAR for the fix or do we have to reinstall GS entirely?

**Comment by aaime** [comment] 2021-12-06 10:43
[2.19.4 is due in 12 days](https://github.com/geoserver/geoserver/wiki/Release-Schedule) but yes, if they don't want to upgrade, I can prepare a patched jar. Just let me know.

**Comment by simboss** [comment] 2021-12-06 11:06
@aaime a patch would be great for short term testing then we can plan to upgrade and retest everything

**Comment by tdipisa** [comment] 2021-12-06 11:15
> @aaime a patch would be great for short term testing then we can plan to upgrade and retest everything

I'm on the same line @aaime, please provide the patched jar as soon as possible.

**Comment by aaime** [comment] 2021-12-06 12:05
Here you go: https://www.dropbox.com/s/66n3qg25htlvcyd/gs-gwc-2.19.1-comunege.jar?dl=1

Remove ``gs-gwc-2.19.1.jar`` and replace it with ``gs-gwc-2.19.1-comunege.jar``. Restart GeoServer.
Customer branch is here: https://github.com/geosolutions-it/geoserver/tree/C040_2.19.1

**Comment by tdipisa** [comment] 2021-12-06 15:43
Thank you @aaime. @randomorder can you please let me know when one of the devops can proceed with the installation of the patch?

**Comment by randomorder** [comment] 2021-12-07 11:30
let's discuss during our usual weekly planning

**Comment by randomorder** [comment] 2021-12-14 16:53
patch deployed

**Closed by randomorder** 2021-12-14 16:53 UTC
Labels: Priority: High, Support Request, C040-COMUNE_GE-2021-SUPPORT, DevOps
