### ISSUE TITLE
GeoServer + GeoFence Update (test)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#443] opened 2021-06-14 09:37 UTC
### Description
Update of the GeoServer cluster to the last stable version. The same update we did last time is needed for this  and it should include the following:
- JDK update
- Tomcat update
- Enable Marlin renderer 
- Also the update of **GeoFence** is needed for this due to some GS DTO updates (to use the GeoFence version compatible with the GS version installed, [here](https://github.com/geoserver/geofence/wiki/Compatibility-matrix-(GS-2.17-2.19,-GF-3.4.x-3.5.x)) the compatibility matrix)

### Other useful information (optional):
The[ deployment documentation](https://docs.google.com/document/d/1-VDOZV0WKOmgPwd4lPTJ2787eMbQ_ljiGVWyegPxq_k/edit#heading=h.z3jdmets1pt7) tells about GS plugins to install.

**Build Info of the current GS installed are reported below**
![image.png](https://images.zenhubusercontent.com/5cd59eb418690954352b7621/535d0127-eff5-41eb-9c82-5c25f3810a83)

**Comment by randomorder** [comment] 2021-07-06 09:22
@drumbsd

I'll show you how to access the infrastructure and brief you on the task before moving on with implementation.

Before we have the talk make sure you have access to the Khttps://drive.google.com/drive/folders/0B8-1l36sVKJeV2VsSk5VZjVHbHM?resourcekey=0-p4qR7TthHy7W4ukYpgd7rg, the VPN set up and SSH access to the machines and you skim through the following docs:
 - [Infrastructure Diagram](https://docs.google.com/drawings/d/14HSuUpFO-j_Bl4hjoXOOTzmXkpoLkMfGdbT_kOiLfU4/edit)
 - [machines setup doc](https://docs.google.com/document/d/1-VDOZV0WKOmgPwd4lPTJ2787eMbQ_ljiGVWyegPxq_k/edit)

We'll prepare the web applications for GeoServer and GeoFence together, then schedule the update and you're going to perform the update of the web applications on the machine taking the necessary backups and updating the documentation. We'll then test the applications together with @tdipisa.

Latest stable GeoServer version [is 2.19.1](https://geoserver.org/) [compatible GeoFence version is 3.5.0](https://github.com/geoserver/geofence/wiki/Compatibility-matrix-(GS-2.17-2.19,-GF-3.4.x-3.5.x))

**Comment by randomorder** [comment] 2021-07-07 09:34
moving on with the update in Test @tdipisa

**Comment by tdipisa** [comment] 2021-07-07 09:38
@randomorder after the update please take care of  #463 as I have requested. Thank you so much.

**Comment by drumbsd** [comment] 2021-07-08 10:11
@randomorder About this documentation:

https://github.com/geoserver/geofence/wiki#installing-geofence

I don't know if it still used, but I think it needs to be updated. For example, this part:

![image](https://user-images.githubusercontent.com/6428880/124904742-9974b700-dfe5-11eb-8dad-ba294001c3aa.png)

These links are not working.

**Comment by drumbsd** [comment] 2021-07-08 10:12
Issue is temporary blocked due to issue with VPN access. We are waiting a feedback from the customer.

**Comment by drumbsd** [comment] 2021-07-09 07:40
UPDATE: It seems that some files under gwc-layers are preventing the geoserver 2.19.1 from starting correctly. We are therefore proceeding to create a script to extract the list of problematic .xml files.

**Comment by drumbsd** [comment] 2021-07-09 09:05
Script is running, even if currently I can't check the output due to issue on VPN connection.

**Comment by drumbsd** [comment] 2021-07-09 10:15
VPN issues has been solved but still persist problem connecting to the Oracle instance. I'm going to move this issue in blocked. I'll restart work on it next monday.

**Comment by drumbsd** [comment] 2021-07-09 17:06
A bash script is currently extracting a list of problematic xml. They are located under

**Comment by drumbsd** [comment] 2021-07-12 13:00
Geoserver should be up and running. Finally we found a problem related to a misconfiguration about gwc config directory. Documentation has been updated with the steps that fix the problem. I'm going to update geofence too.

**Comment by drumbsd** [comment] 2021-07-12 15:22
@randomorder UPDATE: Having some problem with the new release of Geofence. For some strange reasons I got this error 

`org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'org.springframework.beans.factory.config.PropertyOverrideConfigurer#2' defined in URL [jar:file:/var/lib/tomcats/geofence/webapps/geofence/WEB-INF/lib/geofence-persistence-3.5.0.jar!/applicationContext-geofenceDatasource.xml]: Could not resolve placeholder 'geofence-datasource-file' in string value "file:${geofence-datasource-file}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'geofence-datasource-file' in string value "file:${geofence-datasource-file}"`

After read documentation, I tried to override the configuration with an additional JAVA_OPTS, in this way (as written in documentation):

`JAVA_OPTS="-Dgeofence-ovr=file:/var/lib/tomcats/geofence/webapps/geofence/WEB-INF/classes/geofence-datasource-ovr.properties -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses -Xmx1024m -XX:MaxPermSize=128m -Duser.timezone=GMT"`

Still same error. Since the error refers to a variable called "geofence-datasource-file", I changed the JAVA_OPTS from -Dgeofence-ovr to -Dgeofence-datasource-file. After that, the error changed:

`12-Jul-2021 14:58:36.413 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
        org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geofenceEntityManagerFactory' defined in URL [jar:file:/var/lib/tomcats/geofence/webapps/geofence/WEB-INF/lib/geofence-persistence-3.5.0.jar!/applicationContext-geofenceDatasource.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: geofence] Unable to build EntityManagerFactory
`
After some other attempts, changing the row from:

`geofenceEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=validate`

to

`geofenceEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=update`

has cleared the error and geofence *seems* to be correctly executed. Don't know why with -Dgeofence-ovr the software don't start, maybe documentation needs to be updated.

**Comment by randomorder** [comment] 2021-07-12 15:26
please talk with @etj about this issue. He'll explain to you

**Comment by drumbsd** [comment] 2021-07-13 08:23
@randomorder I move this issue under review column for final tests.

**Comment by randomorder** [comment] 2021-07-13 10:33
There's a problem with GF release 3.5.0 @tdipisa @drumbsd 

Is it not starting up. I am able to reproduce the issue we're having in ComGE Test env locally with a vanilla Apache Tomcat 7 and a vanilla GF 3.5.0:
![image](https://user-images.githubusercontent.com/5264230/125437359-8b517d77-5354-40ea-bf8a-8186e6301ec6.png)

The update is blocked at the moment. I am in touch with @etj to investigate the problem

**Comment by etj** [comment] 2021-07-13 16:39
https://github.com/geoserver/geofence/issues/178

If we have a build server somewhere, the 3.5.x nightly can be tried.

**Comment by randomorder** [comment] 2021-07-14 07:29
Nightly should be available [here](https://build.geoserver.org/view/geofence/job/geofence-3.5.x-nightly/)

I am trying it out now

**Comment by randomorder** [comment] 2021-07-14 07:35
running locally on my workstation @etj 
![image](https://user-images.githubusercontent.com/5264230/125582026-87e57b91-50ac-4fc6-9b49-fb28f3961fae.png)

do you plan to release today?

**Comment by randomorder** [comment] 2021-07-14 13:39
In agreement with @etj, we're going to use the nightly build and move on with the setup.
Back to the ready state

**Comment by drumbsd** [comment] 2021-07-15 07:35
Starting to work in the latest geofence 3.5.x. Still issue with VPN connection.

**Comment by drumbsd** [comment] 2021-07-15 09:07
@randomorder  Using the latest nightly the program didn't report the previous error but still got an error , that seems related to this issue:

https://github.com/geoserver/geofence/issues/87

I removed , according to what is described in this issue, the file persistence-api-1.0.jar from lib/, restarted geofence and now it works. Speaking with @etj he asked me to reopen that issue explaining that the problem still persist.

**Comment by drumbsd** [comment] 2021-07-15 09:50
@randomorder For the moment I created a new .war removing persistence-api-1.0.jar from WEB-INF/lib manually as suggested by @etj and redeployed on test server. Now it works. Let me know if this story can be moved under review.

**Comment by tdipisa** [comment] 2021-07-15 10:02
> @randomorder Using the latest nightly the program didn't report the previous error but still got an error , that seems related to this issue:
> 
> [geoserver/geofence#87](https://github.com/geoserver/geofence/issues/87)
> 
> I removed , according to what is described in this issue, the file persistence-api-1.0.jar from lib/, restarted geofence and now it works. Speaking with @etj he asked me to reopen that issue explaining that the problem still persist (problem related to persistence-api-1.0.jar)

@etj let's talk about that please. We cannot go in prod with a limping GF

**Comment by etj** [comment] 2021-07-15 13:47
Dependency removed in GeoFence 3.5.x (https://github.com/geoserver/geofence/issues/87#ref-commit-fd84705)

I suggest using the WAR prepared by @drumbsd by removing the jar by hand (the commit simply removes the dependency and the war does not have that jar anymore). That war can be used in a testing enviroment, and if working can be moved to production.

As noted in https://github.com/geoserver/geofence/issues/87, the issue is related to a race condition, and it was not found before on our side.

**Comment by randomorder** [comment] 2021-07-19 08:22
This is ready for testing @tdipisa

**Comment by tdipisa** [comment] 2021-07-19 10:51
@randomorder thank you, we will proceed with testing this asap. Moved to test in related WS.

**Comment by ElenaGallo** [comment] 2021-07-21 12:22
@tdipisa There is a GeoFence error while loading layers

**How to Reproduce**

Steps in the gif below:
![GEOF3](https://user-images.githubusercontent.com/56537133/126487352-e2ceac1c-f602-4742-89ef-08791ae79b5f.gif)

*Current Result*
It is not possible to add a layer in a GeoFence rule

**Comment by tdipisa** [comment] 2021-07-21 12:58
@ElenaGallo ok, I will review your final test report at the end of your test run to schedule all needed checks.

**Comment by tdipisa** [comment] 2021-07-21 13:17
For the above, it seems anyway that the CSW request made by MS to retrieve the list of layers is failing with this error:

![image](https://user-images.githubusercontent.com/1280027/126494682-c976eed3-ed69-4923-8459-dbbb29ab73ca.png)

Therefore, I don't think it is a problemof GeoFence but something related to the new MS version of maybe the new GS version, or both. @ElenaGallo please open a dedicated issue for this reporting what you wrote above and the result of my investigation.

**Comment by ElenaGallo** [comment] 2021-07-21 13:27
Closed in favor of #465

**Closed** 2021-07-21 13:28 UTC
Labels: Accepted, C040-COMUNE_GE-2021-SUPPORT, DevOps, Priority: High, Task
